name: casl_fit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  modal_bottom_sheet: ^3.0.0
  pull_to_refresh: ^2.0.0
  pinput: ^5.0.1
  gap: ^3.0.1
  flutter_easyloading: ^3.0.5
  oktoast: ^3.4.0
  auto_size_text: ^3.0.0
  fl_chart: ^0.69.0
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  font_awesome_flutter: ^10.8.0
  easy_rich_text: ^2.2.0
  freedom_table: ^0.3.6+3
  carousel_slider: ^5.0.0
  carousel_indicator_simple: ^1.0.0
  flutter_native_splash: ^2.4.4
  webview_flutter: ^4.10.0

  # Animations
  flutter_bounce: ^1.1.0
  flutter_animator: ^3.2.2
  auto_animated: ^3.2.0
  animate_icons: ^2.0.0
  loading_animation_widget: ^1.3.0
  lottie: ^3.3.1

  # Localization
  easy_localization: ^3.0.7+1

  # Networking
  dio: ^5.8.0+1

  # Models
  equatable: ^2.0.7

  # State management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0

  # Local storage
  shared_preferences: ^2.5.3
  cached_network_image: ^3.3.1

  # Security
  encrypt: ^5.0.3

  # Helpers
  flutter_screenutil: ^5.9.0
  mask_text_input_formatter: ^2.9.0
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  number_text_input_formatter: ^1.0.0+8
  meta: ^1.11.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  qr_flutter: ^4.1.0
  pretty_dio_logger: ^1.4.0
  timer_count_down: ^2.2.2

  # Services
  vibration: ^3.1.3
  local_auth: ^2.2.0
  package_info_plus: ^7.0.0
  url_launcher: ^6.2.6
  persistent_bottom_nav_bar_v2: ^5.3.1

  # Navigation
  go_router: ^14.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.5.2

dependency_overrides:
  intl: ^0.19.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/translations/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

flutter_native_splash:
  color: "#324252"
  image: assets/images/logo.png
  android: true
  ios: true